language: python

python:
  - "2.7"

cache: pip

install:
  - pip install -r dependencies.txt

notifications:
    slack: imperium-se:mBOzfUzNqfrDwonqXmBzg4Nl
    email: false

script: export PYTHONPATH=`pwd`; cd test; py.test
